/**
 * Game state enumeration
 * Defines all possible states the game can be in
 */
export const GameState = {
    INTRO: 'INTRO',
    SETTINGS: 'SETTINGS',
    MENU: 'MENU',
    PLAYING: 'PLAYING',
    PAUSED: 'PAUSED',
    GAME_OVER: 'GAME_OVER',
    SINGLE_PLAYER: 'SINGLE_PLAYER',
    TRANSITIONING: 'TRANSITIONING',
    BACKGROUND_SELECTION: 'BACKGROUND_SELECTION',
    PADDLE_SELECTION: 'PADDLE_SELECTION',
    RIGHT_PADDLE_SELECTION: 'RIGHT_PADDLE_SELECTION',
    FIRST_ACCESS: 'FIRST_ACCESS',
    DEBUG: 'DEBUG',
    GAME_MODE_SELECTION: 'GAME_MODE_SELECTION',
    RANK: 'RANK',
    HISTORY: 'HISTORY',
    CIRCLE_MODE_MENU: 'CIRCLE_MODE_MENU',
    CIRCLE_MODE: 'CIRCLE_MODE',
    ADVANCEMENT: 'ADVANCEMENT'
};
